# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 200, 300, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuD_zenle = QtWidgets.QMenu(self.menubar)
        self.menuD_zenle.setObjectName("menuD_zenle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionYeni = QtWidgets.QAction(MainWindow)
        self.actionYeni.setObjectName("actionYeni")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionKaydet = QtWidgets.QAction(MainWindow)
        self.actionKaydet.setObjectName("actionKaydet")
        self.actionKopyala = QtWidgets.QAction(MainWindow)
        self.actionKopyala.setObjectName("actionKopyala")
        self.actionYap_t_r = QtWidgets.QAction(MainWindow)
        self.actionYap_t_r.setObjectName("actionYap_t_r")
        self.menuDosya.addAction(self.actionYeni)
        self.menuDosya.addAction(self.actionA)
        self.menuDosya.addAction(self.actionKaydet)
        self.menuD_zenle.addAction(self.actionKopyala)
        self.menuD_zenle.addAction(self.actionYap_t_r)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuD_zenle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.actionYeni.triggered.connect(lambda: self.clicked("Yeni komutu çalıştırıldı"))
        self.actionA.triggered.connect(lambda: self.clicked("Aç komutu çalıştırıldı"))
        self.actionKaydet.triggered.connect(lambda: self.clicked("Kaydet komutu çalıştırıldı"))
        self.actionKopyala.triggered.connect(lambda: self.clicked("Kopyala komutu çalıştırıldı"))
        self.actionYap_t_r.triggered.connect(lambda: self.clicked("Yapıştır komutu çalıştırıldı"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "Metin"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.menuD_zenle.setTitle(_translate("MainWindow", "Düzenle"))
        self.actionYeni.setText(_translate("MainWindow", "Yeni"))
        self.actionYeni.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionA.setText(_translate("MainWindow", "Aç"))
        self.actionA.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.actionKaydet.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionKopyala.setText(_translate("MainWindow", "Kopyala"))
        self.actionKopyala.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionYap_t_r.setText(_translate("MainWindow", "Yapıştır"))
        self.actionYap_t_r.setShortcut(_translate("MainWindow", "Ctrl+V"))
    def clicked(self,text):
        self.lineEdit.setText(text)
        self.lineEdit.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
